### ISSUE TITLE
Free Form Markup Field for Profile

### ISSUE THREAD

**Issue by cstrotm** [GeraldWodni/forth-ev.de#1]
Hi,

it would be nice to have a free form field in the user profile that can be used to link to (personal) website, Twitter, Mastodon etc etc

Carsten

**Comment by GeraldWodni** [comment]
Profile _details_ now editable via [/profile](https://neu.forth-ev.de/profile), an example can be seen in  [my profile](https://neu.forth-ev.de/~fiz)

**Comment by GeraldWodni** [comment]
fixed over 2 years ago, issue closed ;)
