### ISSUE TITLE
Markdown funktioniert im "Körper" eines Artikels nicht

### ISSUE THREAD

**Issue by cstrotm** [GeraldWodni/forth-ev.de#11]
Im "Intro" eines Artikels kann Markdown verwendet werden, aber im "Körper" wird das Markdown nicht interpretiert. Wird der Markdown-Text in das Intro kopiert, so wird das Markdown korrekt interpretiert und Links und Bilder angezeigt. Im Körper wird der Markdown-Quellcode angezeigt.

**Comment by GeraldWodni** [comment]
Ist als Typ `Markdown` ausgewählt?
Wenn nicht kannst du mir bitte die ID des Artikels sagen oder einfach einen Link wo ich ihn finde?

(Hab in den Code geschaut, aber keinen offensichtlichen Fehler gefunden, deswegen bitte ein Beispiel)
