### ISSUE TITLE
Bilder der Tagungen sind verschwunden

### ISSUE THREAD

**Issue by cstrotm** [GeraldWodni/forth-ev.de#12]
Im Menue unter https://forth-ev.de/albums

Wird ein Album ausgewaehlt, so erscheint:

500 Internal Server Error

We messed something up and are trying to fix it. Please stand by.

Jupiter cluster

**Comment by GeraldWodni** [comment]
Alben auf separate PVC kopiert, jetzt auch im Cluster verfügbar. Siehe commit 3bbd7077deeb0466de9eb7b553dff4ec9192be5d
