### ISSUE TITLE
Image-URL as an alternative to Gravatar

### ISSUE THREAD

**Issue by cstrotm** [GeraldWodni/forth-ev.de#2]
Hi,

it would be nice to be able to link to a self hosted Avartar image as an alternative to Gravatar.

-- Carsten

**Comment by GeraldWodni** [comment]
Fixed in 5f9d50d2cc236448a41eff8d709e6c64c03a1441

**Comment by cstrotm** [comment]
Funktioniert in der Benutzeransicht, aber nicht in der Artikel-Ansicht.

Es scheint als ob der CustomAvatar nicht korrekt uebergeben wird
