### ISSUE TITLE
Images uploaded to /images/articles/2019 not found

### ISSUE THREAD

**Issue by cstrotm** [GeraldWodni/forth-ev.de#5]
Images uploaded through the Media Function of kern.js

![Screen Shot 2019-05-15 at 14 18 04 pm](https://user-images.githubusercontent.com/141758/57775115-9559f100-771c-11e9-95e5-f6a17057575f.png)

when uploading to 

![Screen Shot 2019-05-15 at 14 18 53 pm](https://user-images.githubusercontent.com/141758/57775161-b4f11980-771c-11e9-98bc-0b000708fe0e.png)

seem to work in the beginning

![Screen Shot 2019-05-15 at 14 19 08 pm](https://user-images.githubusercontent.com/141758/57775185-c33f3580-771c-11e9-8d97-724bc8f71411.png)

but if the picture is clicked in the media browser or referenced in an article just returns HTTP Error 404

![Screen Shot 2019-05-15 at 14 19 25 pm](https://user-images.githubusercontent.com/141758/57775269-ebc72f80-771c-11e9-918c-04fde3b80c6f.png)

Uploading the same image to the folder /images succeeds without issues.

**Comment by GeraldWodni** [comment]
/images/articles/* was redirected to the article-image folder of the old website.

- images have been migrated into new repo (only ~5M)
- redirects have been removed
