### ISSUE TITLE
Start- und Ende-Datum von Artikeln koennen nur von Rechnern/Browsern mit Deutscher "locale" eingetragen werden

### ISSUE THREAD

**Issue by cstrotm** [GeraldWodni/forth-ev.de#7]
Das JavaScript Kalender-Popup erzeugt lokalisierte Datumsformate, aber nur ein europaeisches/Deutsches Datum wird genommen.

**Comment by GeraldWodni** [comment]
Habe ich per Email mit Michael repariert. Das aktuelle Format wird jetzt zusätzlich auch als placeholder angezeigt.
